--- #YAML:1.0
name:               Proc-Simple
version:            1.25
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Handle:  0
    Test::More:  0
resources:
    repository:  http://github.com/mschilli/proc-simple-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
